### ISSUE TITLE
Blazon Generator's code doesn't create animals

### ISSUE THREAD

**Issue by Metaillusion** [Tobe-Continued/KingdomTwoCrowns_Blazon_Generator#1]
When I paste the code from the Blazon Generator into the game, the resulting blazon doesn't have the animal part of the blazon. proper.log attached.
[proper.log](https://github.com/Tobe-Continued/KingdomTwoCrowns_Blazon_Generator/files/2698307/proper.log)

**Comment by ghost** [comment]
[Fixed with 1.0.1.0 version](https://github.com/Tobe-Continued/KingdomTwoCrowns_Blazon_Generator/releases/tag/v1.0.1.0)
